services:
  master-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master_server_container
    ports:
      - "50052:50052"
    networks:
      - file_network
    volumes:
      - master_data:/data
    command: ["./masterserver"]

volumes:
  master_data:

networks:
  file_network:
    driver: bridge
