services:
  chunkserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chunk_server_container
    ports:
      - "50051:50051"
    networks:
      - file_network
    environment:
      - SERVER_ID=chunk1
      - STORAGE_PATH=/data
      - MASTER_ADDRESS=172.21.0.2:50052  # ✅ Ensure this matches Master Server
    volumes:
      - chunk_data:/data
    command: ["/app/chunkserver"]

volumes:
  chunk_data:

networks:
  file_network:
    driver: bridge
