services:
  chunkserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: chunk_server_container_2
    ports:
      - "50053:50053"
    networks:
      - shared_file_network
    environment:
      - SERVER_ID=chunk2
      - STORAGE_PATH=/data
      - MASTER_ADDRESS=master_server_container:50052 
    volumes:
      - chunk_data:/data
    command: ["/app/chunkserver"]

volumes:
  chunk_data:

networks:
  shared_file_network:
    external: true
